language: php
php:
  - 5.6
before_install:
  - mysql -e 'create database test;'
install:
  - composer install --prefer-source --no-interaction
scripts:
  - php artisan migrate --env="testing"
  - php artisan db:seed --class=InitSeeder --env="testing"
services:
  - mysql